version: "2"
services:
#  tokenizer:
#    build: ./vnTokenizer
#    command: /bin/bash -c "cd /vnTokenizer/service/ && python service.py"
#    volumes:
#      - ./vnTokenizer:/vnTokenizer
#    ports:
#      - 8080:8080
#  jvn:
#    build: ./jvnSegmenter
#    command: /bin/bash -c "cd /jvnSegmenter/service/ && python service.py"
#    volumes:
#      - ./jvnSegmenter:/jvnSegmenter
#    ports:
#      - 8081:8081
  pyvi:
    build: ./pyvi
    command: /bin/bash -c "cd /pyvi/service/ && python service.py"
#    command: tail -f /dev/null
    volumes:
      - ./pyvi:/pyvi
    ports:
      - 8082:8082
