version: "2"
services:
  jvn:
    build: ./vnTokenizer
    command: /bin/bash -c "cd /vnTokenizer/service/ && python service.py"
    volumes:
      - ./vnTokenizer:/vnTokenizer
    ports:
      - 8080:8080

